materiasCursadas([
        calculoDiferencial, 
        fundamentosProgramacion,
        tallerEtica,
        matematicasDiscretas,
        tallerAdministracion,
        fundamentosInvestigacion,
        actividadesComplementarias
    ]).
semestreActual(2).